spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/sock
    username: user
    password: qwerty
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml


