version: '3'

services:
  postgres-db:
    image: postgres
    container_name: sock-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=sock
    ports:
      - '5435:5432'